name: absen_siswa
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=2.18.6 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  firebase_core: ^2.4.1
  firebase_auth: ^4.2.5
  cloud_firestore: ^4.3.1
  firebase_storage: ^11.0.10
  get_cli: ^1.8.1
  get: 4.6.5
  image_picker: 0.8.6+1
  convex_bottom_bar: ^3.2.0
  intl: ^0.17.0
  geocoding: 2.0.5
  syncfusion_flutter_datepicker: 19.4.56

  flutter:
    sdk: flutter
  geolocator: ^9.0.2

  # syncfusion_flutter_datepicker: ^20.4.49

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.11.0

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/location.png"
  min_sdk_android: 21

flutter:
  uses-material-design: true

assets:
  - assets/images/
  # - ../../../../assets/images/
  # -../../../../assets/images/
